// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	ioc2 "github.com/to404hanga/online_judge_controller/cmd/controller/ioc"
	"github.com/to404hanga/online_judge_controller/event"
	"github.com/to404hanga/online_judge_controller/ioc"
	"github.com/to404hanga/online_judge_controller/service"
	"github.com/to404hanga/online_judge_controller/web"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func BuildDependency() *web.GinServer {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := ioc.InitJWTHandler(cmdable)
	db := ioc.InitDB()
	competitionService := service.NewCompetitionService(db, cmdable, logger)
	rankingService := ioc2.InitRankingService(db, cmdable, logger)
	competitionHandler := web.NewCompetitionHandler(competitionService, rankingService, handler, logger)
	problemService := service.NewProblemService(db, cmdable, logger)
	problemHandler := ioc.InitProblemHandler(problemService, logger)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := event.NewSaramaProducer(syncProducer)
	submissionService := service.NewSubmissionService(db, cmdable, producer, logger)
	submissionHandler := ioc.InitSubmissionHandler(submissionService, competitionService, logger)
	healthHandler := web.NewHealthHandler(logger)
	ginServer := ioc2.InitGinServer(logger, handler, db, competitionHandler, problemHandler, submissionHandler, healthHandler)
	return ginServer
}
