// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	ioc2 "github.com/to404hanga/online_judge_controller/cmd/cronjob/ioc"
	"github.com/to404hanga/online_judge_controller/ioc"
	"github.com/to404hanga/online_judge_controller/job"
	"github.com/to404hanga/online_judge_controller/service"
)

// Injectors from wire.go:

func InitScheduler() *job.CronScheduler {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	cmdable := ioc2.InitNilRedis()
	problemService := service.NewProblemService(db, cmdable, logger)
	producer := ioc2.InitNilKafka()
	submissionService := service.NewSubmissionService(db, cmdable, producer, logger)
	cronScheduler := ioc2.InitScheduler(logger, problemService, submissionService)
	return cronScheduler
}
